version:  '3.7'

services:
    node1:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./node1:/var/lib/mysql
            - ./config/grastate.dat:/var/lib/mysql/grastate.dat
            - ./config/my.node1.cnf:/etc/mysql/conf.d/galera.cnf
        command: --wsrep-new-cluster
        ports: 
            - 3306
            - 4567
            - 4568
            - 4444
        networks: 
            cluster:
                aliases: 
                    - node1.localhost
    node2:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./node2:/var/lib/mysql
            - ./config/my.node2.cnf:/etc/mysql/conf.d/galera.cnf
        ports: 
            - 3306
            - 4567
            - 4568
            - 4444
        networks: 
            cluster:
                aliases: 
                    - node2.localhost
    node3:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./node3:/var/lib/mysql
            - ./config/my.node3.cnf:/etc/mysql/conf.d/galera.cnf
        ports: 
            - 3306
            - 4567
            - 4568
            - 4444
        networks: 
            cluster:
                aliases: 
                    - node3.localhost


networks: 
    cluster: