version: '3.7'

services:
  maria-master:
    image: mariadb:latest
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./backups:/backups
      - ./config/master.cnf:/etc/mysql/mariadb.conf.d/master.cnf
      - ./script:/script
    networks:
      - mynetwork

  maria-slave:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./maria:/var/lib/mysql
      - ./backups:/backups
      - ./script:/script
    networks:
      - mynetwork
networks:
  mynetwork: